#######################################################################################################################
################# This code generates figure4 and figure5, based on results of survival analysis ######################
#######################################################################################################################


```{r}
library(ggplot2)
library(dplyr)
```

#################################
########## Figure 4  ############
#################################
```{r}

## Hazard ratio ##

data <- data.frame(
  Biomarker = rep(c("IFN-γ (pg/ml)","Spike-MBC (%)","nAb","Anti-S-IgG (U/ml)" ), each = 6),
  Study_Period = rep(rep(c("30D-3M", "3M-6M", "6M-12M"), each = 2), times = 4),
  Condition = rep(c("including hybrid immune children", "vaccine-only children"), times = 12),
  Hazard_Ratio = c(
  
    # IFN-γ (pg/ml)
    1.12, 1.12, 0.11, 0.17, 0.19, 0.35,
  # Spike-MBC (%)
    4.11, 4.11, 0.02, 0.04, 9.66, 8.07,
    # nAb
    0.06, 0.06, 0.18, 1.38, 0.26, 2.17,
        # Anti-S-IgG (U/ml)
    0.13, 0.13, 0.16, 0.57, 0.42, 5
    
  ),
  CI_lower = c(
     # IFN-γ (pg/ml)
    0.43, 0.43, 0.04, 0.05, 0.09, 0.13,
    
    # Spike-MBC (%)
    0.87, 0.87, 0.001, 0.004, 0.94, 0.4,
   # nAb
    0.004, 0.004, 0.06, 0.25, 0.09, 0.40,
    # Anti-S-IgG (U/ml)
    0.02, 0.02, 0.06, 0.12, 0.19, 0.57
  ),
  CI_upper = c(
     # IFN-γ (pg/ml)
    2.9, 2.9, 0.3, 0.55, 0.39, 0.95,
    # Spike-MBC (%)
    19, 19, 0.3, 0.59, 98, 161,
    # nAb
    0.81, 0.89, 0.57, 7, 0.76, 11,
    # Anti-S-IgG (U/ml)
    0.65, 0.70, 0.47, 2.60, 0.91, 43
  ),
  Significance = c(
    # IFN-γ (pg/ml)
    "", "", "***", "**", "***", "*",
    
    # Spike-MBC (%)
    "", "", "**", "*", "", "",
    # nAb
    "*", "*", "**", "", "*", "",
    # Anti-S-IgG (U/ml)
    "*", "*", "***", "", "*", ""
  )
)

# Set factor levels so IgG is at the top, IFN-γ at the bottom
data$Biomarker <- factor(data$Biomarker,
                         levels = c("IFN-γ (pg/ml)","Spike-MBC (%)","nAb","Anti-S-IgG (U/ml)" ))

# Assign alpha based on significance
data$alpha <- ifelse(data$Significance == "", 0.3, 1)

# x positions for dodging
dodge_width <- 0.15
data <- data %>%
  mutate(x_pos = as.numeric(Biomarker) +
           ifelse(Condition == "including hybrid immune children", -dodge_width, dodge_width))

# Plot
coeff_plot <- ggplot(data, aes(x = x_pos, y = Hazard_Ratio, color = Condition)) +
  
  geom_errorbar(data = subset(data, CI_upper <= 2),
                aes(ymin = CI_lower, ymax = CI_upper),
                width = 0.2) +
  
  geom_errorbar(
    data = subset(data, CI_upper > 2),
    aes(ymin = CI_lower, ymax = Hazard_Ratio), 
    width = 0.2
  ) +
  
  geom_segment(data = subset(data, CI_upper > 2),
               aes(x = x_pos, xend = x_pos, y = Hazard_Ratio, yend = 2),
               arrow = arrow(length = unit(0.15, "cm"), ends = "last", type = "closed"),
               lineend = "round", linewidth = 0.5) +
  
  geom_segment(data = subset(data, Hazard_Ratio > 2),
               aes(x = x_pos, xend = x_pos, y = CI_lower, yend = 2),
               arrow = arrow(length = unit(0.15, "cm"), ends = "last", type = "closed"),
               lineend = "round", linewidth = 0.5) +
  
  geom_point(size = 4) +
  geom_text(aes(label = Significance, y = 1.2),
            vjust = 0.6, size = 5, color = "black") +
  
  geom_hline(yintercept = 1, linetype = "dotted", color = "black") +
  
  scale_y_continuous(limits = c(0, 2)) +
  scale_alpha_identity() +
  coord_flip() +
  facet_wrap(~Study_Period) +
  scale_x_continuous(breaks = 1:4, labels = levels(data$Biomarker)) +
  theme_minimal() +
  theme(
    axis.text = element_text(colour = "black", size = 14),
    axis.ticks = element_line(colour = "black"),
    axis.line = element_line(colour = "black"),
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    panel.background = element_blank(),
    legend.position = "bottom",
    legend.title = element_blank(),
    strip.text = element_text(size = 14, face = "bold"),
    legend.text = element_text(size = 12),
    axis.title.x = element_text(size = 14),
    axis.title.y = element_text(size = 14)
  ) +
  labs(y = "Hazard Ratio", x = "Biomarker")

coeff_plot

```

#################################
########## Figure 5 A ###########
#################################
```{r}
coeff_data <- data.frame(
  Biomarker = rep(c("IFNg", "Spike-MBC", "nAb", "Anti-S-IgG"), each = 3),
  Study_Period = rep(c("30D-3M", "3M-6M", "6M-12M"), times = 4),
  Coeff_Statistic = c(
    # IFNg
    0.04412, -0.8065, -0.4732,
    # Spike-MBC
    0.3407, -0.6073, 0.3851,
    # nAb
    -0.6654, 0.1244, 0.4222,
    # Anti-S-IgG
    -0.6300, -0.2505, 0.9897
  ),
  Significance = c(
    # IFNg
    "", "**", "*",
    # Spike-MBC
    "", "*", "",
    # nAb
    "*", "", "",
    # Anti-S-IgG
    "*", "", ""
  )
)

coeff_data$Study_Period <- factor(coeff_data$Study_Period,
                                  levels = c("30D-3M", "3M-6M", "6M-12M"))
coeff_data$Biomarker <- factor(coeff_data$Biomarker,
                               levels = c("IFNg", "Spike-MBC", "nAb", "Anti-S-IgG"))
coeff_data$alpha <- ifelse(coeff_data$Significance == "", 0.3, 0.8)
coeff_data$group <- ifelse(coeff_data$Significance == "", "insignificant", "significant")

# Load ggplot2
library(ggplot2)

# Plot the bar chart
coeff_plot1 <- ggplot(coeff_data, aes(x = Biomarker, y = Coeff_Statistic , fill = group, color = group)) +
  geom_bar(stat = "identity", position = position_dodge(width = 1.5)) +
  geom_text(aes(label = Significance), hjust = 1.5, size = 6, color = "black") + 
  labs(
    y = "Coefficient"
  ) +
  coord_flip() +
  facet_wrap(~Study_Period) +
  scale_alpha_identity() +
  scale_fill_manual(values = c("significant" = "#00008B", "insignificant" = "#ADD8E6")) +  # Dark blue for sig, light blue for insig
  scale_color_manual(values = c("significant" = "#00008B", "insignificant" = "#ADD8E6")) + # Same for border
  scale_y_continuous(expand = expansion(mult = 0.3)) + 
  theme_minimal() +
  theme(
    axis.text = element_text(colour = "black", size = 12),
    axis.ticks = element_line(colour = "black"),
    axis.line = element_line(colour = "black"),
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    panel.background = element_blank(),
    legend.position = "bottom",
    legend.title = element_blank(),
    strip.text = element_text(size = 14, face = "bold"),
    legend.text = element_text(size = 12),
    axis.title.x = element_text(size = 14),
    axis.title.y = element_text(size = 14),
    plot.margin = margin(t = 1, r = 1, b = 1, l = 1, unit = "cm")
  )

# Print the plot
print(coeff_plot1)
```

#################################
########## Figure 5 B ###########
#################################
```{r}

coeff_data <- data.frame(
  Biomarker = rep(c("IFNg", "Spike-MBC", "nAb", "Anti-S-IgG"), each = 3),
  Study_Period = rep(c("30D-3M", "3M-6M", "6M-12M"), times = 4),
  Coeff_Statistic = c(
    # IFNg
    0.01889, -1.0213, -0.7555,
    # Spike-MBC
    0.3339, -0.7622 , 0.4181,
    # nAb
    -0.6785, -0.6591 , -0.7308,
    # Anti-S-IgG
    -0.6432, -0.8082 , -0.5322

  ),
  Significance = c(
    # IFNg
    "","***","***",
    # Spike-MBC
    "","**","",
    # nAb
    "*","**","*",
    # Anti-S-IgG
    "*","***","*"

  )
)

coeff_data$Study_Period <- factor(coeff_data$Study_Period, levels = c("30D-3M", "3M-6M", "6M-12M"))
coeff_data$Biomarker <- factor(coeff_data$Biomarker, 
                               levels = c("IFNg", "Spike-MBC", "nAb", "Anti-S-IgG"))
coeff_data$alpha <- ifelse(coeff_data$Significance == "", 0.3, 0.8)
coeff_data$group <- ifelse(coeff_data$Significance == "", "insignificant", "significant")

# Load ggplot2
library(ggplot2)

# Plot the bar chart
coeff_plot1 <- ggplot(coeff_data, aes(x = Biomarker, y = Coeff_Statistic , fill = group, color = group)) +
  geom_bar(stat = "identity", position = position_dodge(width = 1.5)) +
  geom_text(aes(label = Significance), hjust = 1.5, size = 6, color = "black") + 
  labs(
    y = "Coefficient"
  ) +
  coord_flip() +
  facet_wrap(~Study_Period) +
  scale_alpha_identity() +
  scale_fill_manual(values = c("significant" = "#00008B", "insignificant" = "#ADD8E6")) +  # Dark blue for sig, light blue for insig
  scale_color_manual(values = c("significant" = "#00008B", "insignificant" = "#ADD8E6")) + # Same for border
  scale_y_continuous(expand = expansion(mult = 0.3)) + 
  theme_minimal() +
  theme(
    axis.text = element_text(colour = "black", size = 12),
    axis.ticks = element_line(colour = "black"),
    axis.line = element_line(colour = "black"),
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    panel.background = element_blank(),
    legend.position = "bottom",
    legend.title = element_blank(),
    strip.text = element_text(size = 14, face = "bold"),
    legend.text = element_text(size = 12),
    axis.title.x = element_text(size = 14),
    axis.title.y = element_text(size = 14),
    plot.margin = margin(t = 1, r = 1, b = 1, l = 1, unit = "cm")
  )

# Print the plot
print(coeff_plot1)

```
